services:
  app:
    build: .
    container_name: listmonk_app
    restart: unless-stopped
    ports:
      - "9000:9000"
    networks:
      - listmonk
    depends_on:
      - db
    # Forces installation on first run, then starts app
    command: [sh, -c, "./listmonk --install --idempotent --yes && ./listmonk"]
    environment:
      LISTMONK_app__address: 0.0.0.0:9000
      LISTMONK_db__user: listmonk
      LISTMONK_db__password: listmonk
      LISTMONK_db__database: listmonk
      LISTMONK_db__host: db
      LISTMONK_db__port: 5432
      LISTMONK_db__ssl_mode: disable
      LISTMONK_ADMIN_USER: admin
      LISTMONK_ADMIN_PASSWORD: admin
    volumes:
      - ./uploads:/listmonk/uploads:rw

  db:
    image: postgres:17-alpine
    container_name: listmonk_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: listmonk
      POSTGRES_PASSWORD: listmonk
      POSTGRES_DB: listmonk
    networks:
      - listmonk
    volumes:
      - listmonk-data:/var/lib/postgresql/data

networks:
  listmonk:

volumes:
  listmonk-data: